name: visivallet
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  dev: ^1.0.0
  file_picker: ^10.0.0
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_scalable_ocr: ^2.2.1
  freezed_annotation: ^2.4.4
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  google_mlkit_text_recognition: ^0.14.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.5
  phone_form_field: ^10.0.6
  share_plus: ^7.2.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.32

dev_dependencies:
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.jpg"
    background_color: "#ffffff"
    theme_color: "#E85431"
  windows:
    generate: true
    image_path: "assets/logo.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.jpg"
